### ISSUE TITLE
Parse error when running

### ISSUE THREAD

**Issue by weex** [btcspry/3d-wallet-generator#1]
Not getting any STL output.

```
$ ./3DGen.py -co 1
Status: Done generating data for wallet #1...Starting generating STL file
Parser error in line 5: syntax error

Status: Done generating STL file (100% done)
```

Using OpenSCAD version 2014.01.29 on Ubuntu

**Comment by weex** [comment]
I stopped it from removing temp.scad and it seems to have a problem parsing this line, specifically the r=((x+y)/2)*0.052; part.

module roundCornersCube(x,y,z){translate([x/2,y/2,z/2]){difference(){r=((x+y)/2)*0.052;cube([x,y,z],center=true);translate([x/2-r,y/2-r]){rotate(0){createMeniscus(z,r);}}translate([-x/2+r,y/2-r]){rotate(90){createMeniscus(z,r);}}translate([-x/2+r,-y/2+r]){rotate(180){createMeniscus(z,r);}}translate([x/2-r,-y/2+r]){rotate(270){createMeniscus(z,r);}}}}}

**Comment by btcspry** [comment]
Try removing the module parts at the top completely, and then manually running the OpenSCAD line on its own.  Those parts at the top are only necessary if you're using the '-rc' flag.

I didn't have an issue like that, I'm curious what's going on.

**Comment by weex** [comment]
If I remove the top module lines completely so it looks like 

```
// SCAD Code Generated By 3DGen.py - 3D Wallet Generator

// Import some modules

difference() {

cube([86.4,54.0,8.0]); ...more code after
```

Then it renders a blank cube with no qr code on it.

**Comment by weex** [comment]
Looks like I need a newer version of openscad to support the resize module.

**Comment by weex** [comment]
Upgraded and it works now. Thanks!

**Comment by btcspry** [comment]
Thanks! Glad you got it working.

Just to clarify, does it work even with the module part at the top?

**Comment by weex** [comment]
Yes, I was able to run the code from the repo without error once I upgaded my openscad.
