### ISSUE TITLE
Suggestion: Add some images to your README showing the outcome

### ISSUE THREAD

**Issue by gary-rowe** [btcspry/3d-wallet-generator#2]
Great project! In order to garner interest (and stars) quickly I'd suggest updating your README.md with some images of the final printed build. Yes, I know you're exposing private keys but it'll help people to get on board faster.

**Comment by btcspry** [comment]
Thanks for the compliment!  We will work on getting some images up, but as we don't have a very nice printer, we're looking for other people who would but some images up as well.  If you want to print one and take a picture, we'll gladly accept it!
